
name: deploy to lambda
on: [push]
jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
            python-version: '3.9'
      - name: zip
        run: |
          cd ./src
          python -m pip install --upgrade pip
          pip install --target . -r requirements.txt
          zip -r ../lambda.zip ./
          cd ..
      - name: Upload to S3
        uses: medlypharmacy/s3-artifacts-action@master
        with:
          SOURCE_PATH: './lambda.zip'
          AWS_REGION: 'us-west-1'
          AWS_S3_BUCKET_NAME: 'news-artifacts-kvh'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DESTINATION_PATH: "./lambda.zip"
      - name: Install dependencies for update code step and update function code
        run: |
            cd deployment
            python -m pip install --upgrade pip
            pip install --target . -r requirements.txt
            python updateFunctionCode.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-west-1"

