name: deploy to lambda
on: [push]
jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    steps:
#      - name: Make artifact directory
#        run: mkdir -p ./artifacts/cron-data-getter

      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
            python-version: '3.9'
      - name: Create Zip File
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -r lambda.zip ./

      - name: Upload to S3
        uses: medlypharmacy/s3-artifacts-action@master
        with:
          source_path: './lambda.zip'
          aws_region: 'us-west-1'
          aws_s3_bucket_name: 'news-artifacts-kvh'
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
