name: deploy to lambda
on: [push]
jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - name: Make artifact directory
        run: mkdir -p ./artifacts
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
            python-version: '3.9'
      - name: zip
        run: |
          python -m pip install --upgrade pip
          pip install --target . -r requirements.txt
          zip -r ./artifacts/lambda.zip ./
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.3.1
        env:
          SOURCE_DIR: './artifacts'
          AWS_REGION: 'us-west-1'
          AWS_S3_BUCKET: 'news-artifacts-kvh'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
